### ISSUE TITLE
Callback to tell if there are more pages

### ISSUE THREAD

**Issue by amirkhan81** [pklauzinski/jscroll#159]
Is there a method to detect if the current "page" is the last one available?

**Comment by pklauzinski** [comment]
That all depends on the format of your server response, which the plugin has no knowledge of. You can use the [`callback`](https://jscroll.com/#/configuration?id=callback) option thought to parse the response in order to determine if it is the last page and respond accordingly.

Additionally, if your [`nextSelector`](https://jscroll.com/#/configuration?id=nextselector) is not found in your server response, that is usually a good indicator that it is the last page and will also instruct jScroll to unbind from that element.
