### ISSUE TITLE
Loads content early

### ISSUE THREAD

**Issue by dmasson** [pklauzinski/jscroll#36]
This is the URL to reproduce:

http://test.plumaz.com/library/

I begin to scroll down and more content rows appear below before the getting to the scrolling point , .. 

What am I doing wrong ?

**Comment by pklauzinski** [comment]
This sounds like a CSS issue and not an issue with jScroll specifically.

**Comment by faizshukri** [comment]
After few hours digging on this weird issue, I found that the problem was caused by doctype is not correct (or not set). So it’s not a valid HTML so to speak. JQuery cannot calculate window height / document height correctly if doctype is not specified on window

Just put correct doctype above html tag and it will solve the problem.
```html
<!DOCTYPE html>
<html>
...
</html>
```

**Comment by pklauzinski** [comment]
Thank you, @faizshukri.

**Comment by solusipse** [comment]
Just had same problem on my bootstrap template, clearing fixed it. @pklauzinski maybe you should consider adding such information to `README`?

**Comment by milepanic** [comment]
@faizshukri thank you, I am working in Laravel so I included header before section tag
