### ISSUE TITLE
other plugin and event bindings on loaded page content is not working

### ISSUE THREAD

**Issue by saqueib** [pklauzinski/jscroll#63]
I have some plugin on returned page content, but its not working when page load from ajax. I have tried using callback and then it works but performance get slow.

Is there any option to get the ajax response, so I can attach my plugin on the response itself, not on hole page on every page load. Something like below will be helpful.

         callback : function(res, status){
                  //callback should have the response and xhr object 
                  get the response and do the plugin binding 
                  $(res).bind(event)....
         }

Please let me know if you have any better way to deal with this.

**Comment by enoversum** [comment]
Sorry to hook into your post here, but the problem is of similar kind. How do I actually insert a re-call for a plugin (in my case bxSlider) as a callback in jscroll? Adding the needed JS inline into the container that is being loaded actually gets stripped out by jscroll entirely (which would be some kind of workaround).

**Comment by pklauzinski** [comment]
Yes, jScroll provides a `callback` option.
