### ISSUE TITLE
Autotrigger doesn't fetch next content when body/html are 100% height

### ISSUE THREAD

**Issue by peaeater** [pklauzinski/jscroll#85]
In order to accommodate a background image that covers the entire viewport, I have set body and html to height: 100% on my page. When I do this, the jscroll autotrigger does not fetch the next page of results. Jscroll works fine when I remove the 100% height CSS.

Is there a way to have my cake and eat it too? Some workaround to get the autotrigger to work while retaining 100% height on body/html?

**Comment by britiger** [comment]
I've the same problem with the following css on an outer div:
```
position: absolute; 
width: 50%;
bottom: 0px;
left: 0px;
top: 0px;
overflow: auto;	
```
if I remove it, my page don't stop loading like #79

**Comment by sltmunky69** [comment]
I too have this problem.

**Comment by sltmunky69** [comment]
I had a similar problem on a Wordpress site I was building with 100% height that I thought might have been this issue, but it turned out that I added the scroll class to the wrong parent container element. I was using autotrigger to append MySQL results to a page and couldn't get it to work, but once I put it on the correct element and added an additional scroll class ('.scroll-next') on the child element where the results were being displayed and set the contentSelector to that, everything worked great.
